use crate::project::{FileEntry, Project, Stack};

pub fn base_files(project: &Project) -> Vec<FileEntry> {
    vec![
        text_file("README.md", readme(project)),
        text_file(".env", env_file(project)),
        text_file(".env.example", env_file(project)),
        text_file(".gitignore", gitignore(project)),
        text_file(".dockerignore", dockerignore(project)),
        text_file("Makefile", makefile(project)),
        text_file("compose.yaml", compose_file(project)),
        text_file(".github/workflows/ci.yml", ci_workflow(project)),
        text_file("nginx/default.conf", nginx_conf(project)),
    ]
}

pub fn executable_file(path: &'static str, contents: impl Into<String>) -> FileEntry {
    FileEntry {
        path,
        contents: contents.into(),
        executable: true,
    }
}

pub fn text_file(path: &'static str, contents: impl Into<String>) -> FileEntry {
    FileEntry {
        path,
        contents: contents.into(),
        executable: false,
    }
}

pub fn python_dockerfile() -> String {
    r#"FROM python:3.12-slim
WORKDIR /workspace/app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
RUN apt-get update && apt-get install -y build-essential libpq-dev curl && rm -rf /var/lib/apt/lists/*
COPY app/requirements.txt /tmp/requirements.txt
RUN pip install --upgrade pip && pip install -r /tmp/requirements.txt
CMD ["sh", "/workspace/docker/start.sh"]
"#
    .to_string()
}

fn readme(project: &Project) -> String {
    let extra = match project.stack {
        Stack::Node => {
            "The generated app includes Express, BullMQ, Postgres wiring, Redis, an nginx edge, and a worker service."
        }
        Stack::Django => {
            "The generated app includes Django, Postgres, Redis, Celery worker and beat processes, and an nginx edge."
        }
        Stack::Flask => {
            "The generated app includes Flask, Postgres, Redis, Celery worker and beat processes, and an nginx edge."
        }
        Stack::Fastapi => {
            "The generated app includes FastAPI, Postgres, Redis, Celery worker and beat processes, and an nginx edge."
        }
    };

    format!(
        r#"# {}

Generated by DevStack for {}.

{}

## Quickstart

```bash
docker compose up --build
```

The application is available at `http://localhost`.

## Included

- Dockerized app runtime
- Postgres with persistent storage
- Redis for caching and jobs
- Background worker service
- GitHub Actions CI
- `.env` and `.env.example`
- Opinionated project layout for shipping fast

## Handy commands

```bash
make up
make down
make logs
make app-shell
make db-shell
```

## Layout

```text
app/
docker/
nginx/
.github/workflows/
compose.yaml
Makefile
```
"#,
        project.title_name(),
        project.stack.label(),
        extra
    )
}

fn env_file(project: &Project) -> String {
    format!(
        r#"APP_NAME={}
APP_ENV=development
APP_PORT={}
POSTGRES_DB={}
POSTGRES_USER=devstack
POSTGRES_PASSWORD=devstack
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
REDIS_URL=redis://redis:6379/0
SECRET_KEY=change-me-now
ALLOWED_HOSTS=localhost,127.0.0.1
CORS_ORIGINS=http://localhost,http://127.0.0.1
CELERY_BROKER_URL=redis://redis:6379/0
CELERY_RESULT_BACKEND=redis://redis:6379/1
"#,
        project.slug,
        project.stack.app_port(),
        project.stack.database_name(&project.slug)
    )
}

fn gitignore(project: &Project) -> String {
    match project.stack {
        Stack::Node => r#"node_modules
.env
.DS_Store
dist
coverage
"#
        .to_string(),
        Stack::Django | Stack::Flask | Stack::Fastapi => r#"__pycache__/
*.pyc
.pytest_cache/
.venv/
.env
.DS_Store
"#
        .to_string(),
    }
}

fn dockerignore(project: &Project) -> String {
    match project.stack {
        Stack::Node => r#"node_modules
npm-debug.log
.git
"#
        .to_string(),
        Stack::Django | Stack::Flask | Stack::Fastapi => r#"__pycache__/
*.pyc
.venv/
.git
"#
        .to_string(),
    }
}

fn makefile(project: &Project) -> String {
    format!(
        r#"up:
	docker compose up --build

down:
	docker compose down

logs:
	docker compose logs -f

rebuild:
	docker compose build --no-cache

app-shell:
	{}

db-shell:
	docker compose exec postgres sh -lc 'psql -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"'
"#,
        project.stack.app_shell()
    )
}

fn compose_file(project: &Project) -> String {
    let app_extra_volume = if project.stack.uses_node_modules_volume() {
        "      - node_modules:/workspace/app/node_modules\n"
    } else {
        ""
    };

    let worker_services = if project.stack.uses_beat() {
        python_worker_services()
    } else {
        node_worker_service()
    };

    let volumes = if project.stack.uses_node_modules_volume() {
        r#"
volumes:
  postgres_data:
  redis_data:
  node_modules:
"#
    } else {
        r#"
volumes:
  postgres_data:
  redis_data:
"#
    };

    format!(
        r#"services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: sh /workspace/docker/start.sh
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./app:/workspace/app
      - ./docker:/workspace/docker
{app_extra_volume}    expose:
      - "{}"

{}  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${{POSTGRES_DB}}
      POSTGRES_USER: ${{POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{POSTGRES_PASSWORD}}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${{POSTGRES_USER}} -d $${{POSTGRES_DB}}"]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
{}"#,
        project.stack.app_port(),
        worker_services,
        volumes
    )
}

fn node_worker_service() -> &'static str {
    r#"
  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: sh /workspace/docker/worker.sh
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./app:/workspace/app
      - ./docker:/workspace/docker
      - node_modules:/workspace/app/node_modules
"#
}

fn python_worker_services() -> &'static str {
    r#"
  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: sh /workspace/docker/worker.sh
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./app:/workspace/app
      - ./docker:/workspace/docker

  beat:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: sh /workspace/docker/beat.sh
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./app:/workspace/app
      - ./docker:/workspace/docker
"#
}

fn ci_workflow(project: &Project) -> String {
    match project.stack {
        Stack::Node => r#"name: ci

on:
  push:
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install dependencies
        working-directory: app
        run: npm install
      - name: Syntax check
        working-directory: app
        run: |
          node --check src/index.js
          node --check src/worker.js
      - name: Validate Compose
        run: docker compose config
      - name: Build containers
        run: docker compose build
"#
        .to_string(),
        Stack::Django | Stack::Flask | Stack::Fastapi => r#"name: ci

on:
  push:
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
      - name: Compile source
        run: python -m compileall app
      - name: Validate Compose
        run: docker compose config
      - name: Build containers
        run: docker compose build
"#
        .to_string(),
    }
}

fn nginx_conf(project: &Project) -> String {
    format!(
        r#"server {{
    listen 80;
    server_name _;
    client_max_body_size 32m;

    location / {{
        proxy_pass http://app:{};
        proxy_http_version 1.1;
        proxy_set_header Host $$host;
        proxy_set_header X-Real-IP $$remote_addr;
        proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $$scheme;
        proxy_set_header Upgrade $$http_upgrade;
        proxy_set_header Connection "upgrade";
    }}
}}
"#,
        project.stack.app_port()
    )
}
